# Generated by Django 3.1.4 on 2020-12-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201203_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='text',
            field=models.TextField(max_length=700),
        ),
    ]
